export enum Configuration {
    PORT = 'PORT',
    PORT_DB = 'PORT_DB',
    HOST = 'HOST',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    DATABASE_PRIMARY = 'DATABASE_PRIMARY',
    DATABASE_SECONDARY = 'DATABASE_SECONDARY',
    JWT_SECRET = 'JWT_SECRET'
}
